services:
  php-apache:
    build:
      context: .
      dockerfile: ./docker/php/php-dockerfile
      args:
        LOG_FILE_NAME: ${LOG_FILE_NAME}.log
    ports:
      - ${PHP_PORT}
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  mariadb:
    image: mariadb:10.4.27
    env_file:
      - .env    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Prague
    ports:
      - ${MARIADB_PORT}
    command: ['--character-set-server=utf8', '--collation-server=utf8_czech_ci', '--max_allowed_packet=1024M']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${MARIADB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 1024M
      TZ: Europe/Prague
    ports:
      - ${PHP_MY_ADMIN_PORT}
    depends_on:
      - mariadb
